#!/usr/bin/env python
import sys

from meitrack.common import DIRECTION_CLIENT_TO_SERVER, SERVER_TO_CLIENT_PREFIX, DIRECTION_SERVER_TO_CLIENT, s2b
from meitrack.gprs_protocol import parse_data_payload, calc_signature

if __name__ == "__main__":

    for gprs_item in sys.stdin:
        gprs_item = s2b(gprs_item)
        gprs_item = b':'.join(gprs_item.split(b':')[3:])[3:].replace(b'\\n', b'\n').replace(b'\\r', b'\r')[:-2]
        print(gprs_item)
        direction = DIRECTION_CLIENT_TO_SERVER
        if gprs_item[0:2] == SERVER_TO_CLIENT_PREFIX:
            direction = DIRECTION_SERVER_TO_CLIENT
        test_gprs_list, before_bytes, extra_bytes = parse_data_payload(gprs_item, direction)
        for gprs in test_gprs_list:
            print(gprs)
            print("============================================================================================")
            print(gprs.as_bytes())
        if before_bytes:
            print("Before bytes is ", before_bytes)
        if extra_bytes:
            print("Leftover is ", extra_bytes)
        if b"AAA" in gprs_item:
            print(gprs.enclosed_data["longitude"])
            print(gprs.enclosed_data.longitude)

        print(hex(calc_signature(gprs_item)))